services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: api-service/Dockerfile
      platforms:
        - linux/amd64
    image: barngoose/pulse-api:latest
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db

  worker:
    build:
      context: .
      dockerfile: worker-service/Dockerfile
      platforms:
        - linux/amd64
    image: barngoose/pulse-worker:latest
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db

  notifs:
    build:
      context: .
      dockerfile: notifs-service/Dockerfile
      platforms:
        - linux/amd64
    image: barngoose/pulse-notifs:latest
    ports:
      - "8001:8001"
    environment:
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      ALERT_FROM_EMAIL: ${ALERT_FROM_EMAIL}
      ALERT_TO_EMAIL: ${ALERT_TO_EMAIL}

volumes:
  postgres_data:
