apiVersion: v1
kind: Secret
metadata:
  name: pulse-secrets
type: Opaque
stringData:
  POSTGRES_USER: youruser
  POSTGRES_PASSWORD: yourpass
  POSTGRES_DB: yourdb
  DB_HOST: yourhost
  DB_PORT: "5432"
  SENDGRID_API_KEY: your_sendgrid_key_here
  ALERT_FROM_EMAIL: your_from_email@gmail.com
  ALERT_TO_EMAIL: your_to_email@gmail.com
  NOTIFS_URL: http://notifs:8001
